version: '3.8'

services:
  # Streamlit application service
  streamlit:
    build: .
    command: streamlit run app.py
    volumes:
      - .:/app
    # Port mapping for Streamlit app
    # Format: "host_port:container_port"
    # Change the left number (8501) to modify the port on your host machine/VPS
    # Example: "9000:8501" would make the app available on port 9000
    ports:
      - "8505:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0

  # Documentation service using MkDocs
  docs:
    build: .
    command: mkdocs serve -a 0.0.0.0:8000
    volumes:
      - .:/app
    # Port mapping for documentation server
    # Format: "host_port:container_port"
    # Change the left number (8000) to modify the port on your host machine/VPS
    # Example: "9001:8000" would make the docs available on port 9001
    ports:
      - "8506:8000"
    environment:
      - PYTHONUNBUFFERED=1
